# See the .env file for config options

# version of docker-compose format, do not change
version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "letsencrypt_data:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - fedimint_network

  bitcoin:
    image: "bitcoin/bitcoin:28.1"
    container_name: "bitcoin"
    volumes:
      - bitcoind_data:/home/bitcoin/.bitcoin
    ports:
      - "8333:8333"
    command:
      -printtoconsole
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcauth="${BITCOIND_RPC_AUTH}"
      -dbcache=2200
      -prune=550
      -maxmempool=5
      -par=2
      -rpcthreads=4
      -maxconnections=32
      -server=1
    restart: unless-stopped
    networks:
      - fedimint_network

  fedimintd:
    image: ${FEDIMINTD_IMAGE}
    volumes:
      - fedimintd_data:/data
    ports:
      - "0.0.0.0:8173:8173"
    environment:
      - FM_BITCOIN_RPC_KIND=${FM_BITCOIN_RPC_KIND}
      - FM_BITCOIN_RPC_URL=${FM_BITCOIN_RPC_URL}
      - FM_BITCOIN_NETWORK=bitcoin
      - FM_BIND_P2P=0.0.0.0:8173
      - FM_P2P_URL=fedimint://${FM_DOMAIN}:8173
      - FM_BIND_API=0.0.0.0:8174
      - FM_API_URL=wss://${FM_DOMAIN}/ws/
      - FM_REL_NOTES_ACK=0_4_xyz
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fedimintd.loadbalancer.server.port=8174"
      - "traefik.http.routers.fedimintd.rule=Host(`${FM_DOMAIN}`) && Path(`/ws/`)"
      - "traefik.http.routers.fedimintd.entrypoints=websecure"
      - "traefik.http.routers.fedimintd.tls.certresolver=myresolver"
    restart: unless-stopped
    networks:
      - fedimint_network

  guardian-ui:
    image: fedimintui/guardian-ui:0.4.2
    environment:
      - PORT=80
      - REACT_APP_FM_CONFIG_API=wss://${FM_DOMAIN}/ws/
    depends_on:
      - fedimintd
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.guardian-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.guardian-ui.rule=Host(`${FM_DOMAIN}`)"
      - "traefik.http.routers.guardian-ui.entrypoints=websecure"
      - "traefik.http.routers.guardian-ui.tls.certresolver=myresolver"
    restart: unless-stopped
    networks:
      - fedimint_network

networks:
  fedimint_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  bitcoind_data:
  letsencrypt_data:
  fedimintd_data:
